### ISSUE TITLE
Menü Flaschen

### ISSUE THREAD

**Issue by adominator** [AndreWohnsland/AndreWohnsland#1]
Hallo, Nach dem ich 16 Pumpen aktiviert habe ist Im Menü (Flaschen)die Grafik komplett unübersichtlich. Ich denke mit eine Scroll Funktion wäre das Problem behoben. Gruß

**Comment by adominator** [comment]
Hallo, Nach dem ich 16 Pumpen aktiviert habe ist Im Menü (Flaschen)die Grafik komplett unübersichtlich. Ich denke mit eine Scroll Funktion wäre das Problem behoben. Gruß

**Comment by AndreWohnsland** [comment]
Hey adominator,

ich habe dazu ein Feature Request in dem CocktailBerry Repo aufgemacht: https://github.com/AndreWohnsland/CocktailBerry/issues/31 
Dieses Repo ist nur für die Darstellung von meinem GitHub Profil, darum schließe ich es hier :)

An eine Scrollfunktion habe ich auch schon gedacht. Ich denke diese wird mit v1.12.1 implementiert sein - schau einfach, wenn der Issue geschlossen ist, bzw. es ein neues Update gibt.

Gruß

**Comment by adominator** [comment]
Ich danke dir für die schnelle Antwort. Ist zwar nicht fertig aber Ich würde dir gerne mein Projekt vorstellen und Bilder zusenden ![image](https://user-images.githubusercontent.com/6562887/212145753-8e5998e7-9b7c-4d0d-82a6-86a9e03151c6.jpeg)

**Comment by adominator** [comment]
Wie kann ich dir Bilder senden von meinen Projekt um apikey zu bekommen wegen Cocktails Statistik? Gruß

**Comment by AndreWohnsland** [comment]
Das sieht doch schon sehr schön aus! Bekommt der Touchscreen von dem Relay den Strom, oder sieht das nur so aus? Hat das Relay auch einen 12V->5V Converter mit drin, oder ist das kleine rote Board oben drüber der Buck-Converter? Die Pumpen kommen mir auf jedenfalls sehr bekannt vor. 

Du kannst mir auch gerne an cocktailmakeraw@gmail.com schreiben, bzw. dahin einen Kontakt wie Discord, o.Ä. senden (Falls du noch mehr Kommunizieren willst, damit die Daten nicht hier öffentlich stehen), für weitere Kommunikation, das muss ja nicht hier öffentlich sichtbar sein 😬

**Comment by adominator** [comment]
Perfekt ich melde mich morgen bei dir via email. Vielen Dank!

**Comment by adominator** [comment]
Habe dir E-Mail gesendet Gruß

**Comment by adominator** [comment]
Hallo Andre, 2 fragen habe ich an dich:1: wie genau gunktioniert das mit led einrichten habe bereits versucht aber funktioniert nicht kannst du mir link eventuell senden von led ring das auf jeden fall geht falls du mir link hast das ich bestellen kann.2: ich würde gerne Kanister mit 5 Liter Zutaten anschließen aber die Maschine kann ja max bis 1 liter glaub ich eingestellt werden. Meine Vorstellungen ist statt flaschen Kanister anzuschließen wenn mal grosseres feier ist. Gruß Adnan Gesendet mit der WEB.DE Mail AppAm 12.01.23 um 20:25 schrieb Andre Wohnsland
                
            
            
                
                    Von: "Andre Wohnsland" ***@***.***>Datum: 12. Januar 2023An: "AndreWohnsland/AndreWohnsland" ***@***.***>Cc: "Author" ***@***.***>,"adominator" ***@***.***>Betreff: Re: [AndreWohnsland/AndreWohnsland] Menü Flaschen (Issue #1)
                
                

Das sieht doch schon sehr schön aus! Bekommt der Touchscreen von dem Relay den Strom, oder sieht das nur so aus? Hat das Relay auch einen 12V->5V Converter mit drin, oder ist das kleine rote Board oben drüber der Buck-Converter? Die Pumpen kommen mir auf jedenfalls sehr bekannt vor.

Du kannst mir auch gerne an ***@***.*** schreiben, bzw. dahin einen Kontakt wie Discord, o.Ä. senden (Falls du noch mehr Kommunizieren willst, damit die Daten nicht hier öffentlich stehen), für weitere Kommunikation, das muss ja nicht hier öffentlich sichtbar sein 😬
